[firebase]
apiKey = "AIzaSyBLIbfVIw47ymQbt1w1VH_czYG0M9LRGWw"
authDomain = "six-90963.firebaseapp.com"
databaseURL = "https://six-90963-default-rtdb.firebaseio.com"
projectId = "six-90963"
storageBucket = "six-90963.firebasestorage.app"
messagingSenderId = "284795024486"
appId = "1:284795024486:web:6a0a33425adfb9235869a7"
