type = "service_account"
project_id = "six-90963"
private_key_id = "58a6753e3513b75b57738c0bd4665cad0d06d706"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCx+/l+Bmlx+Gfd
... [TRIMMED FOR BREVITY] ...
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@six-90963.iam.gserviceaccount.com"
client_id = "102654105790751411950"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40six-90963.iam.gserviceaccount.com"
database_url = "https://six-90963-default-rtdb.firebaseio.com/"
